### PR TITLE
test(fuzz): add testdata

### PR DESCRIPTION
**Pull request by ernado**
Updates #10

### CODE REVIEW

**Comment by ernado** [comment]
@tdakkota please fix it so I can fuzz it further.

Currently I'm unable to proceed because go std fuzzing does not support multiple crashers.

**Comment by ghost** [comment]
@ernado I've rebased this branch and moved the tag check under the env flag. Now it is possible to continue fuzzing.

**Comment by ernado** [comment]
```
--- FAIL: FuzzDecodeEncodeDecode (6.59s)
    --- FAIL: FuzzDecodeEncodeDecode (0.00s)
        fuzz_test.go:118:
                Error Trace:    /root/yamlx/fuzz_test.go:118
                                                        /root/yamlx/fuzz_test.go:133

                                                        /root/yamlx/value.go:339
                                                        /root/yamlx/fuzz.go:337
                Error:          Not equal:
                                expected: "\n"
                                actual  : "\n\n"

                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -2 +2,2 @@

                                +
                Test:           FuzzDecodeEncodeDecode
        fuzz_test.go:87: Input: "|+\n\n#00000"
        fuzz_test.go:89: Data: "|4+\n\n\n#00000\n"

    Failing input written to testdata/fuzz/FuzzDecodeEncodeDecode/8cf4812e4e6f6f8c0276e10a83403ad06a31dd9d59a344b969bdc7a50e5822d2
    To re-run:
    go test -run=FuzzDecodeEncodeDecode/8cf4812e4e6f6f8c0276e10a83403ad06a31dd9d59a344b969bdc7a50e5822d2
```
Probably should normalize newlines

**Comment by ernado** [comment]
@tdakkota 
```
go test fuzz v1
[]byte("&x\nc: *x")
```

Fuzzing hangs up on this, please check. Probably infinite recursion?

**Comment by ernado** [comment]
```
fuzz: elapsed: 42s, execs: 4084712 (61455/sec), new interesting: 362 (total: 1425)
--- FAIL: FuzzDecodeEncodeDecode (41.95s)
    --- FAIL: FuzzDecodeEncodeDecode (0.00s)
        fuzz_test.go:115:
                Error Trace:    /root/yamlx/fuzz_test.go:115
                                                        /root/yamlx/value.go:556
                                                        /root/yamlx/value.go:339
                                                        /root/yamlx/fuzz.go:337
                Error:          Received unexpected error:
                                yaml: offset 2: did not find expected tag URI
                Test:           FuzzDecodeEncodeDecode
        fuzz_test.go:91: Input: "!<!!>"
        fuzz_test.go:93: Data: "!!\n"

    Failing input written to testdata/fuzz/FuzzDecodeEncodeDecode/daa3fb5eb85b769d93c89ebec33f7aed8714a9ff0929acaef0738972aaba2934
    To re-run:
    go test -run=FuzzDecodeEncodeDecode/daa3fb5eb85b769d93c89ebec33f7aed8714a9ff0929acaef0738972aaba2934
```

```
go test fuzz v1
[]byte("!<!!>")
```

**Comment by ernado** [comment]
```
--- FAIL: FuzzDecodeEncodeDecode (6.28s)
    --- FAIL: FuzzDecodeEncodeDecode (0.00s)
        fuzz_test.go:115:
                Error Trace:    /root/yamlx/fuzz_test.go:115
                                                        /root/yamlx/value.go:556
                                                        /root/yamlx/value.go:339
                                                        /root/yamlx/fuzz.go:337
                Error:          Received unexpected error:
                                yaml: offset 1: did not find expected whitespace or line break
                Test:           FuzzDecodeEncodeDecode
        fuzz_test.go:91: Input: "%TAG ! !,\n--- !0"
        fuzz_test.go:93: Data: "!,0\n"

    Failing input written to testdata/fuzz/FuzzDecodeEncodeDecode/80d7746f8ea58302875df00e90705f229103358f698aeb73f512a7cdf2e3ca6f
    To re-run:
    go test -run=FuzzDecodeEncodeDecode/80d7746f8ea58302875df00e90705f229103358f698aeb73f512a7cdf2e3ca6f
FAIL
exit status 1
FAIL    github.com/go-faster/yamlx      13.103s
```

```
go test fuzz v1
[]byte("%TAG ! !,\n--- !0")
```

**Pull request merged**
